config/routes.rb
Pethero::Application.routes.draw do

  devise_for :users

  resources :homepages do
		resources :comments
  end

   root :to => 'homepages#index'

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name
  field :content
  embedded_in :article, :inverse_of => :comments
end

app/models/homepage.rb
class Homepage
  include Mongoid::Document
  field :name
  field :collegename
  field :published_on, :type => Date
  validates_presence_of :name
  embeds_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @homepage = Homepage.find(params[:homepage_id])
	  @comment = @homepage.comments.create!(params[:comment])
	  redirect_to @homepage, :notice => "Comment created!"
	end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
before_filter :authenticate_user!
  # GET /homepages
  # GET /homepages.json
  def index
    @homepages = Homepage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homepages }
    end
  end

  # GET /homepages/1
  # GET /homepages/1.json
  def show
    @homepage = Homepage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @homepage }
    end
  end

  # GET /homepages/new
  # GET /homepages/new.json
  def new
    @homepage = Homepage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @homepage }
    end
  end

  # GET /homepages/1/edit
  def edit
    @homepage = Homepage.find(params[:id])
  end

  # POST /homepages
  # POST /homepages.json
  def create
    @homepage = Homepage.new(params[:homepage])

    respond_to do |format|
      if @homepage.save
        format.html { redirect_to @homepage, notice: 'Homepage was successfully created.' }
        format.json { render json: @homepage, status: :created, location: @homepage }
      else
        format.html { render action: "new" }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homepages/1
  # PUT /homepages/1.json
  def update
    @homepage = Homepage.find(params[:id])

    respond_to do |format|
      if @homepage.update_attributes(params[:homepage])
        format.html { redirect_to @homepage, notice: 'Homepage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepages/1
  # DELETE /homepages/1.json
  def destroy
    @homepage = Homepage.find(params[:id])
    @homepage.destroy

    respond_to do |format|
      format.html { redirect_to homepages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/_form.html.erb
<%= form_for(@homepage) do |f| %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :collegename %><br />
    <%= f.text_field :collegename %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.text_field :published_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homepages/edit.html.erb
<h1>Editing homepage</h1>

<%= render 'form' %>

<%= link_to 'Show', @homepage %> |
<%= link_to 'Back', homepages_path %>

app/views/homepages/index.html.erb
<h1>Listing homepages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Collegename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @homepages.each do |homepage| %>
  <tr>
    <td><%= homepage.name %></td>
    <td><%= homepage.collegename %></td>
    <td><%= link_to 'Show', homepage %></td>
    <td><%= link_to 'Edit', edit_homepage_path(homepage) %></td>
    <td><%= link_to 'Destroy', homepage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Homepage', new_homepage_path %>

app/views/homepages/new.html.erb
<h1>New homepage</h1>

<%= render 'form' %>

<%= link_to 'Back', homepages_path %>

app/views/homepages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @homepage.name %>
</p>

<p>
  <b>Collegename:</b>
  <%= @homepage.collegename %>
</p>
<p>
  <b>publishedon:</b>
  <%= @homepage.published_on %>
</p>

<% if @homepage.comments.size > 0 %>
  <h2>Comments</h2>
  <% for comm in @homepage.comments %>
    <h3><%= comm.name %></h3>
    <p><%= comm.content %></p>
  <% end %>
<% end %>

<h2>New Comment</h2>
<%= form_for [@homepage, Comment.new] do |f| %>
  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.text_area :content, :rows => 10 %></p>
  <p><%= f.submit %></p>
<% end %>


<%= link_to 'Edit', edit_homepage_path(@homepage) %> |
<%= link_to 'Back', homepages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pethero</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>